// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $ws from "./routes/ws.ts";
import * as $Board from "./islands/Board.tsx";
import * as $GameManager from "./islands/GameManager.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/ws.ts": $ws,
  },
  islands: {
    "./islands/Board.tsx": $Board,
    "./islands/GameManager.tsx": $GameManager,
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
